config/routes.rb
Testapp::Application.routes.draw do
  devise_for :users

  get 'profile' => 'users#profile'
  
  namespace :admin do
    resources :clients do
      resources :stores
    end
    resources :features
    resources :services
  end

  resources :posts

  get 'admin' => 'pages#admin'
  
  root 'pages#home'

  get 'self-storage/' => 'areas#index'
  get 'self-storage/:state' => 'areas#state'
  get 'self-storage/:state/:city' => 'areas#city'

  resources :areas

  

end

app/models/service.rb
class Service < ActiveRecord::Base
belongs_to :store

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "admin"

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to [:admin, @service], notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to [:admin, @service], notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :assigned_to, :status_code, :description, :cost, :start_date, :end_date)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :store_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cost, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :start_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :end_date, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_services_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/services/edit.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/services/index.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:status_code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:cost) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.id, admin_service_path(service) %></td>
        <td><%= service.name %></td>
        <td><%= service.store_id %></td>
        <td><%= service.status_code %></td>
        <td><%= service.description %></td>
        <td><%= service.cost %></td>
        <td><%= service.start_date %></td>
        <td><%= service.end_date %></td>
        <td><%=l service.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_service_path(service), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_service_path(service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_service_path,
            :class => 'btn btn-primary' %>

app/views/admin/services/new.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/services/show.html.erb
<%- model_class = Service -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @service.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:assigned_to) %>:</strong></dt>
  <dd><%= @service.store_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_code) %>:</strong></dt>
  <dd><%= @service.status_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @service.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cost) %>:</strong></dt>
  <dd><%= @service.cost %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @service.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @service.end_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_services_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_service_path(@service), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_service_path(@service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>