config/routes.rb
Testapp::Application.routes.draw do
  devise_for :users

  get 'profile' => 'users#profile'
  
  namespace :admin do
    resources :clients do
      resources :stores
    end
    resources :features
    resources :services
  end

  resources :posts

  get 'admin' => 'pages#admin'
  
  root 'pages#home'

  get 'self-storage/' => 'areas#index'
  get 'self-storage/:state' => 'areas#state'
  get 'self-storage/:state/:city' => 'areas#city'

  resources :areas

  

end

app/views/admin/_clients.html.erb
<%- model_class = Client -%>
<% load_client %>
<ul class="nav nav-list">
  <li class="nav-header">Clients</li>
  <li><%= link_to "<i class='icon-zoom-in'></i>Client Info".html_safe, admin_client_path(@client)  %></li>
  <li><%= link_to "<i class='icon-search'></i>View Clients".html_safe, admin_clients_path  %></li>
  <li><%= link_to "<i class='icon-plus-sign'></i>Add New Client".html_safe, new_admin_client_path  %></li>
</ul>

app/views/admin/_features.html.erb
<%- model_class = Feature -%>

<ul class="nav nav-list">
  <li class="nav-header">Features</li>
  <li><%= link_to "View Store Features", admin_client_store_path(@client, @store)  %></li>
  <li><%= link_to "Assign New Service", "/path2"  %></li>
  <li><%= link_to "Add New Service", "/path3"  %></li>
</ul>

app/views/admin/_services.html.erb
<%- model_class = Service -%>

<ul class="nav nav-list">
  <li class="nav-header">Services</li>
  <li><%= link_to "View Client Services", admin_client_path(@client)  %></li>
  <li><%= link_to "View Store Services", admin_client_store_path(@client, @store)  %></li>
  <li><%= link_to "Assign New Service", "/path2"  %></li>
  <li><%= link_to "Add New Service", "/path3"  %></li>
</ul>

app/views/admin/_stores.html.erb
<%- model_class = Store -%>
<% load_store %>
<ul class="nav nav-list">
  <li class="nav-header">Stores</li>
  <li><%= link_to "<i class='icon-zoom-in'></i>Store Info".html_safe, admin_client_store_path(@client, @store)  %></li>
  <li><%= link_to "<i class='icon-search'></i>View Stores".html_safe, admin_client_stores_path(@client)  %></li>
  <li><%= link_to "<i class='icon-plus-sign'></i>Add New Store".html_safe, new_admin_client_store_path(@client)  %></li>
</ul>