config/routes.rb
Testapp::Application.routes.draw do
  devise_for :users

  get 'profile' => 'users#profile'
  
  namespace :admin do
    resources :clients do
      resources :stores
    end
    resources :features
    resources :services
  end

  resources :posts

  get 'admin' => 'pages#admin'
  
  root 'pages#home'

  get 'self-storage/' => 'areas#index'
  get 'self-storage/:state' => 'areas#state'
  get 'self-storage/:state/:city' => 'areas#city'

  resources :areas

  

end

app/models/area.rb
class Area < ActiveRecord::Base
	

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  layout "area"

  def state
    @states = Store.distinct.order(:state).pluck(:state)

    if !params[:state].nil?
      @cities = Store.distinct.where(:state => params[:state]).order(:city).pluck(:city)
    end
    
    @stores_in_state = Store.where(:state => params[:state])

  end

  def city
    @states = Store.distinct.order(:state).pluck(:state)
    @cities = Store.distinct.where(:state => params[:state]).order(:city).pluck(:city)
    @stores_in_city = Store.where(:state => params[:state], :city => params[:city])
  end

  def states
    @states = Store.distinct.order(:state).pluck(:state)
  end

  def cities
    @cities = Store.distinct.where(:state => params[:state]).order(:city).pluck(:city)
  end

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    @states = Store.distinct.order(:state).pluck(:state)

    if params[:state].nil?
      @cities = Store.distinct.where(:state => params[:state]).order(:city).pluck(:city)
      @stores_in_state = Store.where(:state => params[:state])
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render action: 'show', status: :created, location: @area }
      else
        format.html { render action: 'new' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:display_name, :internal_name, :area_type, :latitude, :longitude)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
	
end

app/views/areas/_cities.html.erb
<%- model_class = Store -%>

<h4>Cities</h4>

<div>
  <%= select_tag("city-select", options_for_select(@cities)) %>
</div>

app/views/areas/_form.html.erb
<%= form_for @area, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :display_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :display_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :internal_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :internal_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :area_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :area_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :latitude, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :longitude, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                areas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/areas/_sidebar.html.erb
<%- model_class = Store -%>

<%= render :partial => 'areas/states' %>
<% if !params[:state].nil? %>
	<%= render :partial => 'areas/cities' %>
<% end %>

app/views/areas/_states.html.erb
<%- model_class = Store -%>

<h4>Select a State</h4>

<div>
  <%= select_tag("state-select", options_for_select(@states, :include_blank => false)) %>
</div>

app/views/areas/city.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1>Self Storage in <%= params[:city] %>, <%= params[:state] %></h1>
</div>

<table id="cities">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:branded_name) %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores_in_city.each do |store| %>
      <tr>
        <td><%= store.branded_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/areas/edit.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/areas/index.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="dataTable">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:display_name) %></th>
      <th><%= model_class.human_attribute_name(:internal_name) %></th>
      <th><%= model_class.human_attribute_name(:area_type) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= link_to area.id, area_path(area) %></td>
        <td><%= area.display_name %></td>
        <td><%= area.internal_name %></td>
        <td><%= area.area_type %></td>
        <td><%= area.latitude %></td>
        <td><%= area.longitude %></td>
        <td><%=l area.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_area_path(area), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      area_path(area),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_area_path,
            :class => 'btn btn-primary' %>

app/views/areas/new.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/areas/show.html.erb
<%- model_class = Area -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:display_name) %>:</strong></dt>
  <dd><%= @area.display_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:internal_name) %>:</strong></dt>
  <dd><%= @area.internal_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:area_type) %>:</strong></dt>
  <dd><%= @area.area_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @area.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @area.longitude %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              areas_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_area_path(@area), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              area_path(@area),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/areas/state.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1>Self Storage in <%= params[:state] %></h1>
</div>

<table id="states">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:branded_name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores_in_state.each do |store| %>
      <tr>
        <td><%= store.branded_name %></td>
        <td><%= link_to store.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>